services:
  - type: web
    name: trading-gemini-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -u bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: BOT_TOKEN
        sync: false
      - key: CLOUDFLARE_ACCOUNT_ID
        sync: false
      - key: CHANNEL_USERNAME
        sync: false
      - key: CLOUDFLARE_API_TOKEN
        sync: false
      - key: CLOUDFLARE_MODEL
        value: "@cf/unum/uform-gen2-qwen-500m"
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
      - key: DATA_DIR
        value: storage
